package aq.koptev.i.util;

public enum TypeNetObject {
    REQUEST_AUTHENTICATION, ERROR_AUTHENTICATION, SUCCESS_AUTHENTICATION,
    REQUEST_REGISTRATION, ERROR_REGISTRATION, SUCCESS_REGISTRATION,
    DISCONNECTION_NOTIFY, MESSAGE;
}
