package aq.project.utils;

public interface AuthorityNames {

	String BASIC_READ_USER = "BASIC_READ_USER";
	String BASIC_UPDATE_USER = "BASIC_UPDATE_USER";
	String BASIC_DELETE_USER = "BASIC_DELETE_USER";
	String EXTENDED_CREATE_USER = "EXTENDED_CREATE_USER";
	String EXTENDED_READ_USER = "EXTENDED_READ_USER";
	String EXTENDED_UPDATE_USER = "EXTENDED_UPDATE_USER";
	String EXTENDED_DELETE_USER = "EXTENDED_DELETE_USER";
	String CREATE_AUTHORITY = "CREATE_AUTHORITY"; 
	String READ_AUTHORITY = "READ_AUTHORITY";
	String UPDATE_AUTHORITY = "UPDATE_AUTHORITY";
	String DELETE_AUTHORITY = "DELETE_AUTHORITY";
}
