logging:
  level:
    org.springframework.security: DEBUG
spring:
  application:
    name: user-service
  profiles:
    active:
    - dev_db_h2
server:
  port: 8558
---
spring:
  config:
    activate:
      on-profile: dev_db_h2
  datasource:
    generate-unique-name: false
    name: user-service-db
    url: jdbc:h2:mem:user-service-db
    driver-class-name: org.h2.Driver
    username: admin 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: dev_db_mem_app
