server:
 port: 8558
spring:
 application:
  name: user-service
 profiles:
  active:
#   - dev_db_h2
#   - dev_db_my_sql
   - dev_liquibase_my_sql
---
spring:
 config:
  activate:
    on-profile: dev_db_h2
 datasource:
   generate-unique-name: false
   name: user_service_db
   url: jdbc:h2:mem:user_service_db
   driver-class-name: org.h2.Driver
   username: admin 
 h2:
  console:
      enabled: true
      path: /h2-console
 jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org.springframework.security: DEBUG
---
spring:
 config:
  activate:
   on-profile: dev_db_my_sql
 datasource:
  name: user_service_db
  url: jdbc:mysql://localhost/user_service_db?createDatabaseIfNotExist=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: root
 jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect 
---
spring:
 config:
  activate:
   on-profile: dev_liquibase_my_sql
 datasource:
  name: user_service_db
  url: jdbc:mysql://localhost/user_service_db?createDatabaseIfNotExist=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: root
 jpa:
  hibernate:
   ddl-auto: none 
  database-platform: org.hibernate.dialect.MySQL8Dialect
 liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
---
spring:
 config:
  activate:
   on-profile: dev_db_mem_app
